#!/usr/bin/env python3

import time
import colors as c

seconds = 1

def show():
    print(c.clear)
    print(c.yellow + '[Press ctrl c to stop!]' + c.reset, end=': ', flush=True)
    print(c.cyan + seconds)

#---------------------------------------------------------------------

show()

while True:
    time.sleep(1)
    seconds += 1
    show()
